# From: https://github.com/pypa/cibuildwheel
name: Upload Python Package

on:
  push:

  release:
    types: [published]

jobs:
  release:
    name: Release
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
